services:
  - type: web
    name: aiag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run --enable-api --cors "*" --port $PORT
    plan: free
    timeout: 600
    branches: main
